name: Go Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.21'
      id: go

    - name: Check out code
      uses: actions/checkout@v3

    - name: Run unit tests
      run: go test -v

    - name: Run basic example
      run: go run ./examples/basic

    - name: Run advanced example
      run: go run ./examples/advanced 