name: Go CI

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Check out code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: go mod download

    - name: Run go vet
      run: go vet ./...

    - name: Run go fmt (Check Formatting)
      run: |
        if [ -n "$(go fmt ./...)" ]; then
          echo "Go fmt issues found!"
          exit 1
        fi
      shell: bash

    - name: Build
      run: go build -v ./...

    - name: Run unit tests
      run: go test -v ./...

    - name: Run race detector (Linux only)
      if: matrix.os == 'ubuntu-latest' && github.event_name == 'push'
      run: go test -race -v ./...

    - name: Run basic example
      run: |
        cd ./examples/basic
        go mod tidy
        go run .

    - name: Run advanced example
      run: |
        cd ./examples/advanced
        go mod tidy
        go run .
