name: Go

on:
  push:
    branches: ["master", "develop"] # Include both branches
  pull_request:
    branches: ["master", "develop"] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21' # Latest stable version is recommended

    - name: Install Dependencies
      run: go mod download

    - name: Run go vet
      run: go vet ./...

    - name: Run go fmt (Check Formatting)
      run: if [ -n "$(go fmt ./...)" ]; then echo "Go fmt issues found!"; exit 1; fi

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test ./... 


    - name: Run race detector
      if: github.event_name == 'push' # Only run race detector on push, not pull requests
      run: go test -race -v ./... 
